### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by adibindrianto** [bling-yshs/Actions-ImmortalWrt#1]
![Screenshot_2024-03-30-19-43-51-05](https://github.com/bling-yshs/Actions-ImmortalWrt/assets/133480318/63bca202-6ca0-42ea-862e-082ccd8c6aa3)
How to fix it?

**Comment by bling-yshs** [comment]
You need to edit the file `.github/workflows/build.yml`. Find the following section:

```
- name: Build immortalwrtARM
  run: |
    cd $REPO_NAME
    make -j$(nproc)
    pwd
    ls
# 默认make -j$(nproc)，代表多线程编译。如果求稳想看报错信息，可以使用make -j1 V=99代替
```

Change `make -j$(nproc)` to `make -j1 V=99`. This is mentioned in the code annotation above. Only then can you see the specific error information

Finally, I haven't compiled ImmortalWrt for a long time, so I'm not very familiar with it anymore. You can look for other Github action repositories while waiting for the compilation.

**Comment by adibindrianto** [comment]
not working, same problem

**Comment by bling-yshs** [comment]
> not working, same problem

Sorry, I found the reason for this problem, it is because the github action compilation environment is incomplete. I have now fixed it and started a compilation action using your `.config`. It is now compiling the firmware (if you still need it). Here is the link:

https://github.com/prettyYs/Actions-ImmortalWrt/actions/runs/8495288153/job/23271401062
